apiVersion: v1
kind: Secret
metadata:
  name: expensy-secrets
  namespace: expensy
type: Opaque
stringData:
  mongo_user: root
  mongo_pass: example
  redis_password: someredispassword
  database_uri: mongodb://root:example@mongo:27017/expensy?authSource=admin